name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend:
    name: Lint, Test & Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        env:
          HUSKY: 0
        run: npm ci

      - name: FSD Validation
        working-directory: ./frontend
        run: npm run fsd-check

      - name: Lint Frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Type Check Frontend
        working-directory: ./frontend
        run: npm run type-check

      - name: Create test env file
        run: |
          echo "VITE_URL=http://localhost" > .env

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  backend:
    name: Lint, Test & Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Backend Dependencies
        working-directory: ./backend
        env:
          HUSKY: 0
        run: npm ci

      - name: Lint Backend
        working-directory: ./backend
        run: npm run lint

      - name: Type Check Backend
        working-directory: ./backend
        run: npm run type-check

      - name: Create test env file
        run: |
          cp .env.example .env
          cp .env ./backend/.env  

      - name: Run Tests
        working-directory: ./backend
        run: npm run test

      - name: Build Backend
        working-directory: ./backend
        run: npm run build
